In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

## HYDERABAD :

In [2]:
names = []
address = []
city = []
features = []
ratings = []
votes = []
prices = []
for i in range(1,6):
        url="https://www.oyorooms.com/hotels-in-hyderabad/?page="+str (i)
        print(url)
        
        page = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
        soup = BeautifulSoup(page.text, 'html.parser')
        
        N = soup.find_all("a", class_="c-nn640c u-width100")
        for i in N:
            a = i.text
            names.append(a)
        
        rat=soup.find_all('div',class_="oyo-cell--12-col listingHotelDescription__content")
        for i in rat:
            a = i.text
            b = re.findall("(\d\.\d)\s\(", a)
            ratings.append(b) 
        
        pr=soup.find_all("span",class_='listingPrice__finalPrice')
        for i in pr:
            a=i.text
            prices.append(a)  
       
        add=soup.find_all("span",class_="u-line--clamp-2")
        for i in add:
            a=i.text
            address.append(a.replace(', Hyderabad', ""))  
            
            
        vo=soup.find_all("div",class_="oyo-cell--12-col listingHotelDescription__content")
        for i in vo:
            a =i.text
            b = re.findall("\((\d+)\sRatings", a)
            votes.append(b)
        ci=soup.find_all("span",class_="u-line--clamp-2")
        for i in ci:
            a=i.text
            city.append(re.findall(r"Hyderabad", a)) 
            
            
        fea = soup.find_all("div", class_="amenityWrapper")
        for i in fea:
            a = i.text
            features.append(a.split("+")[0])

https://www.oyorooms.com/hotels-in-hyderabad/?page=1
https://www.oyorooms.com/hotels-in-hyderabad/?page=2
https://www.oyorooms.com/hotels-in-hyderabad/?page=3
https://www.oyorooms.com/hotels-in-hyderabad/?page=4
https://www.oyorooms.com/hotels-in-hyderabad/?page=5

In [3]:
print(len(names))
print(len(ratings))
print(len(prices))
print(len(address))
print(len(votes))
print(len(city))
print(len(features))

100
100
100
100
100
100
100

In [4]:
dic={"Hotel_Names":names,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [6]:
df=pd.DataFrame(dic)
df

,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,Flagship Malkajgiri,Malkajgiri,[Hyderabad],[4.3],[2269],₹699,Parking facility Reception Free Wifi
1,OYO Flagship Hotel Lavish Stay,New Santoshnagar,[Hyderabad],[4.3],[23],₹582,Free Wifi Geyser Power backup
2,OYO Flagship Hotel Shazeb International,Telangana,[Hyderabad],[3.7],[17],₹699,Elevator Free Wifi Geyser
3,Collection O Hotel Rbs Kothapet-nagole Road,,[Hyderabad],[5.0],[7],₹699,Elevator Free Wifi Geyser
4,OYO Flagship 80983G RBS Square Langer Houz,Hyderabad,"[Hyderabad, Hyderabad]",[3.9],[98],₹699,Free Wifi Geyser Power backup
...,...,...,...,...,...,...,...
95,SPOT ON Hotel Sai Ashirwad Residency,punjagutta,[Hyderabad],[],[],₹1071,Free Wifi Geyser Power backup
96,OYO Flagship New Hotel Aroma Classic,Hyderabad 500001,"[Hyderabad, Hyderabad]",[3.0],[4],₹1062,Elevator Free Wifi Geyser
97,OYO Flagship Hotel R Square,Dilsukhnagarnull,[Hyderabad],[4.0],[214],₹1257,Free Wifi Geyser Power backup
98,OYO Hotel Shannu Residency,"Near Apollo Pharmacy, Secunderabad",[Hyderabad],[4.1],[892],₹1074,Free Wifi Geyser TV
99,Townhouse 1188 Xanthe Hotels,"Ward 98, Sai Baba Temple Road, Sr Nagar, Ward ...",[Hyderabad],[3.4],[136],₹1484,Elevator Free Wifi Geyser

## BANGLORE:

In [7]:
names = []
address = []
city = []
features = []
ratings = []
votes = []
prices = []
for i in range(1,6):
        url="https://www.oyorooms.com/hotels-in-bangalore/?page="+ str (i)
        print(url)
        page = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
        soup = BeautifulSoup(page.text, 'html.parser')
        
        
        N = soup.find_all("a", class_="c-nn640c u-width100")
        for i in N:
            a = i.text
            names.append(a)
        
        rat=soup.find_all('div',class_="oyo-cell--12-col listingHotelDescription__content")
        for i in rat:
            a = i.text
            b = re.findall("(\d\.\d)\s\(", a)
            ratings.append(b) 
        
        pr=soup.find_all("span",class_='listingPrice__finalPrice')
        for i in pr:
            a=i.text
            prices.append(a)  
       
        add=soup.find_all("span",class_="u-line--clamp-2")
        for i in add:
            a=i.text
            address.append(a.replace(', Bangalore', ""))  
            
            
        vo=soup.find_all("div",class_="oyo-cell--12-col listingHotelDescription__content")
        for i in vo:
            a =i.text
            b = re.findall("\((\d+)\sRatings", a)
            votes.append(b)
        ci=soup.find_all("span",class_="u-line--clamp-2")
        for i in ci:
            a=i.text
            city.append(re.findall(r"Bangalore", a)) 
            
            
        fea = soup.find_all("div", class_="amenityWrapper")
        for i in fea:
            a = i.text
            features.append(a.split("+")[0])

https://www.oyorooms.com/hotels-in-bangalore/?page=1
https://www.oyorooms.com/hotels-in-bangalore/?page=2
https://www.oyorooms.com/hotels-in-bangalore/?page=3
https://www.oyorooms.com/hotels-in-bangalore/?page=4
https://www.oyorooms.com/hotels-in-bangalore/?page=5

In [8]:
print(len(names))
print(len(ratings))
print(len(prices))
print(len(address))
print(len(votes))
print(len(city))
print(len(features))

100
100
100
100
100
100
98

## FILLING NAN VALUE:

In [9]:
features.insert(95,np.NaN)
features.insert(98,np.NaN)

In [10]:
print(len(features))

100

In [11]:
dic1={"Hotel_Names":names,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [12]:
df1=pd.DataFrame(dic1)
df1

,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,Home Shiva Shakthi Inn Near Ragigudda Sri Pras...,J P Nagar,[Bangalore],[4.3],[854],₹581,Private entrance Parking facility Elevator
1,SPOT ON Srinivasa Boarding And Lodging Near Vi...,"Near N R Colony, Sajjepalya",[Bangalore],[3.2],[402],₹399,TV
2,Flagship S M Residency Near Mysore Road Metro ...,Nagarbhavi,[Bangalore],[3.4],[323],₹572,Free Wifi Geyser Power backup
3,OYO Flagship 814835 MANYATA INN SERVICE APARTMENT,Karnataka,[Bangalore],[3.9],[34],₹576,Free Wifi Geyser Power backup
4,SPOT ON Balaji Residency near Yeshwantupur Rai...,L N Colony,[Bangalore],[3.4],[314],₹460,AC TV Queen Sized Bed
...,...,...,...,...,...,...,...
95,Capital O Safari Rooms Near Snow City,India Bangalore Karnatakaindia,"[Bangalore, Bangalore]",[3.4],[189],₹1202,NaN
96,OYO 8501 ABHIMAANI COMFORTS,Kanakpura main road metro pillar number 45 nea...,[],[3.5],[227],₹1360,Elevator Free Wifi Geyser
97,OYO Flagship V R Residency Near Sri Amruth Chi...,"Centrally Located, Near 4th block, HBR Layout",[Bangalore],[3.6],[113],₹1216,Parking facility Reception Power backup
98,Flagship Sri Hari Premium Comforts Near Sandhy...,"Near KLM Finvest, HSR layout sector7",[Bangalore],[3.4],[260],₹1360,NaN
99,OYO Flagship Raj Residency,,[Bangalore],[3.0],[4],₹1071,Free Wifi Geyser Power backup

## DELHI:

In [13]:
names = []
address = []
city = []
features = []
ratings = []
votes = []
prices = []
for i in range(1,6):
        url="https://www.oyorooms.com/hotels-in-delhi/?page="+ str (i)
        print(url)
        page = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
        soup = BeautifulSoup(page.text, 'html.parser')
        
        
        N = soup.find_all("a", class_="c-nn640c u-width100")
        for i in N:
            a = i.text
            names.append(a)
        
        rat=soup.find_all('div',class_="oyo-cell--12-col listingHotelDescription__content")
        for i in rat:
            a = i.text
            b = re.findall("(\d\.\d)\s\(", a)
            ratings.append(b) 
        
        pr=soup.find_all("span",class_='listingPrice__finalPrice')
        for i in pr:
            a=i.text
            prices.append(a)  
       
        add=soup.find_all("span",class_="u-line--clamp-2")
        for i in add:
            a=i.text
            address.append(a.replace(', Delhi', ""))  
            
            
        vo=soup.find_all("div",class_="oyo-cell--12-col listingHotelDescription__content")
        for i in vo:
            a =i.text
            b = re.findall("\((\d+)\sRatings", a)
            votes.append(b)
        ci=soup.find_all("span",class_="u-line--clamp-2")
        for i in ci:
            a=i.text
            city.append(re.findall(r"Delhi", a)) 
            
            
        fea = soup.find_all("div", class_="amenityWrapper")
        for i in fea:
            a = i.text
            features.append(a.split("+")[0])

https://www.oyorooms.com/hotels-in-delhi/?page=1
https://www.oyorooms.com/hotels-in-delhi/?page=2
https://www.oyorooms.com/hotels-in-delhi/?page=3
https://www.oyorooms.com/hotels-in-delhi/?page=4
https://www.oyorooms.com/hotels-in-delhi/?page=5

In [14]:
print(len(names))
print(len(ratings))
print(len(prices))
print(len(address))
print(len(votes))
print(len(city))
print(len(features))

100
100
100
100
100
100
99

In [15]:
features.insert(93,np.NaN)

In [16]:
print(len(features))

100

In [17]:
dic2={"Hotel_Names":names,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [18]:
df2=pd.DataFrame(dic2)
df2

,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,Flagship Dream Inn Near Akshardham,J 8 Near Mithila Appartment Chandra Vihar Pat...,"[Delhi, Delhi]",[3.5],[211],₹649,Free Wifi Geyser Power backup
1,Townhouse 868 Dream Connect Near TDI Mall,Wz-3 Opp Pillor No 322 Moti Nagar Delhi,"[Delhi, Delhi]",[4.2],[2828],₹1248,Parking facility Reception Free Wifi
2,OYO Flagship Hotel SS Palace,Block A,[Delhi],[3.9],[284],₹904,AC TV
3,Super OYO Townhouse 381 Dilshad Garden Near Di...,Pocket E,[Delhi],[4.3],[2219],₹1482,AC TV
4,OYO Hotel J Joy,"MAIN FAIZ ROAD (Above SBI BANK), KAROL BAGH",[],[3.6],[1107],₹986,Elevator Reception Free Wifi
...,...,...,...,...,...,...,...
95,Flagship Leisurrestay,I.P.Extension,[Delhi],[3.5],[9],₹2325,AC TV
96,OYO Flagship Golden Petal,Jheel Khurenja Geeta Colony,[Delhi],[3.5],[16],₹2446,Elevator Free Wifi Geyser
97,OYO Happy Inn,Near Shahdara Metro Station,[Delhi],[3.5],[52],₹2325,Private entrance Parking facility Reception
98,Collection O Hotel Swisston Palace,W.E.A Ajmal khan Road Karol Bagh Near Metro P...,[Delhi],[2.9],[19],₹2446,Free Wifi Geyser Power backup
99,OYO Flagship Hotel Vista Inn,WEA Karol Bagh,[Delhi],[3.7],[4],₹2446,Elevator Free Wifi Geyser

## MUMBAI:

In [19]:
names = []
address = []
city = []
features = []
ratings = []
votes = []
prices = []
for i in range(1,5):
        url="https://www.oyorooms.com/hotels-in-mumbai/?page="+ str (i)
        print(url)
        page = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
        soup = BeautifulSoup(page.text, 'html.parser')
        
        
        N = soup.find_all("a", class_="c-nn640c u-width100")
        for i in N:
            a = i.text
            names.append(a)
        
        rat=soup.find_all('div',class_="oyo-cell--12-col listingHotelDescription__content")
        for i in rat:
            a = i.text
            b = re.findall("(\d\.\d)\s\(", a)
            ratings.append(b) 
        
        pr=soup.find_all("span",class_='listingPrice__finalPrice')
        for i in pr:
            a=i.text
            prices.append(a)  
       
        add=soup.find_all("span",class_="u-line--clamp-2")
        for i in add:
            a=i.text
            address.append(a.replace(', Mumbai', ""))  
            
            
        vo=soup.find_all("div",class_="oyo-cell--12-col listingHotelDescription__content")
        for i in vo:
            a =i.text
            b = re.findall("\((\d+)\sRatings", a)
            votes.append(b)
        ci=soup.find_all("span",class_="u-line--clamp-2")
        for i in ci:
            a=i.text
            city.append(re.findall(r"Mumbai", a)) 
            
            
        fea = soup.find_all("div", class_="amenityWrapper")
        for i in fea:
            a = i.text
            features.append(a.split("+")[0])

https://www.oyorooms.com/hotels-in-mumbai/?page=1
https://www.oyorooms.com/hotels-in-mumbai/?page=2
https://www.oyorooms.com/hotels-in-mumbai/?page=3
https://www.oyorooms.com/hotels-in-mumbai/?page=4

In [20]:
print(len(names))
print(len(ratings))
print(len(prices))
print(len(address))
print(len(votes))
print(len(city))
print(len(features))

62
62
60
62
62
62
62

In [21]:
prices.insert(97,np.NaN)
prices.insert(88,np.NaN)

In [22]:
print(len(prices))

62

In [23]:
dic3={"Hotel_Names":names,
   "Address":address,
   "City":city,
   "Ratings":ratings,
   "Votes":votes,
   "Prices":prices,
   "Features":features
  }

In [24]:
df3=pd.DataFrame(dic3)
df3

,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,Flagship The Mumbai Inn Near Chhatrapati Shiva...,The Mumbai Inn 90 Feet Road Next To Peninsula ...,"[Mumbai, Mumbai, Mumbai]",[3.4],[418],₹1399,Hair Dryer Reception Security
1,OYO Flagship 812940 Hotel Nk Grand,Asalpha,[Mumbai],[3.4],[63],₹1359,Free Wifi Geyser Power backup
2,POP 81030D Hotel Crystal Park Jogeshwari Mumbai,"SV ROAD, NEAR JVLR JUNCTION, NEXT TO MARKAZ HO...",[],[3.7],[74],₹1886,Free Wifi Geyser Power backup
3,OYO Flagship Hotel Kailash Park Near Chhatrapa...,"Near Sakinaka Metro station, Andheri East",[Mumbai],[4.0],[124],₹1722,Free Wifi Geyser CCTV cameras
4,Townhouse OAK Hotel Shubhangan Near Juhu Beach,"Hotel Shubhangan-21st road,Khar West",[],[3.5],[63],₹2446,Reception Ticket tour assistance Caretaker
...,...,...,...,...,...,...,...
57,Collection O 815331 Hotel Galaxy Shelter,Prabhadevi. Appasaheb Marathe Marg,[Mumbai],[3.6],[10],₹3902,Elevator Free Wifi Geyser
58,Capital O Hotel Pearl Near US Embassy,"Near Wajan Kata Bus Stop, Indira Nagar",[Mumbai],[3.3],[160],₹2896,Free Wifi CCTV cameras Card payment
59,OYO Townhouse 810 Royal Palms Hotel - Daisy Co...,Goregaon,[Mumbai],[3.6],[494],₹3773,Parking facility Free Wifi Power backup
60,OYO Hotel Ak Palace Near Chhatrapati Shivaji I...,"On main street, Near Asalpha Metro Station, Sa...",[Mumbai],[3.1],[254],NaN,Free Wifi
61,OYO Flagship Raj Hotel Near Juhu Beach,Santacruz,[Mumbai],[3.1],[191],NaN,Free Wifi Geyser Power backup

## CONCATE DATA FRAME :

In [25]:
CON1=pd.concat([df,df1],axis=0)
CON2=pd.concat([df2,df3],axis=0)

In [26]:
final=pd.concat([CON1,CON2],axis=0)

In [27]:
final

,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,Flagship Malkajgiri,Malkajgiri,[Hyderabad],[4.3],[2269],₹699,Parking facility Reception Free Wifi
1,OYO Flagship Hotel Lavish Stay,New Santoshnagar,[Hyderabad],[4.3],[23],₹582,Free Wifi Geyser Power backup
2,OYO Flagship Hotel Shazeb International,Telangana,[Hyderabad],[3.7],[17],₹699,Elevator Free Wifi Geyser
3,Collection O Hotel Rbs Kothapet-nagole Road,,[Hyderabad],[5.0],[7],₹699,Elevator Free Wifi Geyser
4,OYO Flagship 80983G RBS Square Langer Houz,Hyderabad,"[Hyderabad, Hyderabad]",[3.9],[98],₹699,Free Wifi Geyser Power backup
...,...,...,...,...,...,...,...
57,Collection O 815331 Hotel Galaxy Shelter,Prabhadevi. Appasaheb Marathe Marg,[Mumbai],[3.6],[10],₹3902,Elevator Free Wifi Geyser
58,Capital O Hotel Pearl Near US Embassy,"Near Wajan Kata Bus Stop, Indira Nagar",[Mumbai],[3.3],[160],₹2896,Free Wifi CCTV cameras Card payment
59,OYO Townhouse 810 Royal Palms Hotel - Daisy Co...,Goregaon,[Mumbai],[3.6],[494],₹3773,Parking facility Free Wifi Power backup
60,OYO Hotel Ak Palace Near Chhatrapati Shivaji I...,"On main street, Near Asalpha Metro Station, Sa...",[Mumbai],[3.1],[254],NaN,Free Wifi
61,OYO Flagship Raj Hotel Near Juhu Beach,Santacruz,[Mumbai],[3.1],[191],NaN,Free Wifi Geyser Power backup

In [28]:
final=final.reset_index()

In [29]:
final

,index,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,0,Flagship Malkajgiri,Malkajgiri,[Hyderabad],[4.3],[2269],₹699,Parking facility Reception Free Wifi
1,1,OYO Flagship Hotel Lavish Stay,New Santoshnagar,[Hyderabad],[4.3],[23],₹582,Free Wifi Geyser Power backup
2,2,OYO Flagship Hotel Shazeb International,Telangana,[Hyderabad],[3.7],[17],₹699,Elevator Free Wifi Geyser
3,3,Collection O Hotel Rbs Kothapet-nagole Road,,[Hyderabad],[5.0],[7],₹699,Elevator Free Wifi Geyser
4,4,OYO Flagship 80983G RBS Square Langer Houz,Hyderabad,"[Hyderabad, Hyderabad]",[3.9],[98],₹699,Free Wifi Geyser Power backup
...,...,...,...,...,...,...,...,...
357,57,Collection O 815331 Hotel Galaxy Shelter,Prabhadevi. Appasaheb Marathe Marg,[Mumbai],[3.6],[10],₹3902,Elevator Free Wifi Geyser
358,58,Capital O Hotel Pearl Near US Embassy,"Near Wajan Kata Bus Stop, Indira Nagar",[Mumbai],[3.3],[160],₹2896,Free Wifi CCTV cameras Card payment
359,59,OYO Townhouse 810 Royal Palms Hotel - Daisy Co...,Goregaon,[Mumbai],[3.6],[494],₹3773,Parking facility Free Wifi Power backup
360,60,OYO Hotel Ak Palace Near Chhatrapati Shivaji I...,"On main street, Near Asalpha Metro Station, Sa...",[Mumbai],[3.1],[254],NaN,Free Wifi
361,61,OYO Flagship Raj Hotel Near Juhu Beach,Santacruz,[Mumbai],[3.1],[191],NaN,Free Wifi Geyser Power backup

In [30]:
final.drop('index',axis=1,inplace=True)

In [32]:
final

,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,Flagship Malkajgiri,Malkajgiri,[Hyderabad],[4.3],[2269],₹699,Parking facility Reception Free Wifi
1,OYO Flagship Hotel Lavish Stay,New Santoshnagar,[Hyderabad],[4.3],[23],₹582,Free Wifi Geyser Power backup
2,OYO Flagship Hotel Shazeb International,Telangana,[Hyderabad],[3.7],[17],₹699,Elevator Free Wifi Geyser
3,Collection O Hotel Rbs Kothapet-nagole Road,,[Hyderabad],[5.0],[7],₹699,Elevator Free Wifi Geyser
4,OYO Flagship 80983G RBS Square Langer Houz,Hyderabad,"[Hyderabad, Hyderabad]",[3.9],[98],₹699,Free Wifi Geyser Power backup
...,...,...,...,...,...,...,...
357,Collection O 815331 Hotel Galaxy Shelter,Prabhadevi. Appasaheb Marathe Marg,[Mumbai],[3.6],[10],₹3902,Elevator Free Wifi Geyser
358,Capital O Hotel Pearl Near US Embassy,"Near Wajan Kata Bus Stop, Indira Nagar",[Mumbai],[3.3],[160],₹2896,Free Wifi CCTV cameras Card payment
359,OYO Townhouse 810 Royal Palms Hotel - Daisy Co...,Goregaon,[Mumbai],[3.6],[494],₹3773,Parking facility Free Wifi Power backup
360,OYO Hotel Ak Palace Near Chhatrapati Shivaji I...,"On main street, Near Asalpha Metro Station, Sa...",[Mumbai],[3.1],[254],NaN,Free Wifi
361,OYO Flagship Raj Hotel Near Juhu Beach,Santacruz,[Mumbai],[3.1],[191],NaN,Free Wifi Geyser Power backup

In [33]:
final.to_csv("ALL_OYO_RAW_DATA.csv")

## DATA CLEANING:

In [35]:
data=pd.read_csv(r"C:\\Users\\amarn\\ALL_OYO_RAW_DATA.csv")

In [36]:
data

,Unnamed: 0,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,0,Flagship Malkajgiri,Malkajgiri,['Hyderabad'],['4.3'],['2269'],₹699,Parking facility Reception Free Wifi
1,1,OYO Flagship Hotel Lavish Stay,New Santoshnagar,['Hyderabad'],['4.3'],['23'],₹582,Free Wifi Geyser Power backup
2,2,OYO Flagship Hotel Shazeb International,Telangana,['Hyderabad'],['3.7'],['17'],₹699,Elevator Free Wifi Geyser
3,3,Collection O Hotel Rbs Kothapet-nagole Road,NaN,['Hyderabad'],['5.0'],['7'],₹699,Elevator Free Wifi Geyser
4,4,OYO Flagship 80983G RBS Square Langer Houz,Hyderabad,"['Hyderabad', 'Hyderabad']",['3.9'],['98'],₹699,Free Wifi Geyser Power backup
...,...,...,...,...,...,...,...,...
357,357,Collection O 815331 Hotel Galaxy Shelter,Prabhadevi. Appasaheb Marathe Marg,['Mumbai'],['3.6'],['10'],₹3902,Elevator Free Wifi Geyser
358,358,Capital O Hotel Pearl Near US Embassy,"Near Wajan Kata Bus Stop, Indira Nagar",['Mumbai'],['3.3'],['160'],₹2896,Free Wifi CCTV cameras Card payment
359,359,OYO Townhouse 810 Royal Palms Hotel - Daisy Co...,Goregaon,['Mumbai'],['3.6'],['494'],₹3773,Parking facility Free Wifi Power backup
360,360,OYO Hotel Ak Palace Near Chhatrapati Shivaji I...,"On main street, Near Asalpha Metro Station, Sa...",['Mumbai'],['3.1'],['254'],NaN,Free Wifi
361,361,OYO Flagship Raj Hotel Near Juhu Beach,Santacruz,['Mumbai'],['3.1'],['191'],NaN,Free Wifi Geyser Power backup

In [44]:
data.drop('Unnamed: 0',axis=1,inplace=True)

In [45]:
data

,Hotel_Names,Address,City,Ratings,Votes,Prices,Features
0,Flagship Malkajgiri,Malkajgiri,['Hyderabad'],['4.3'],['2269'],₹699,Parking facility Reception Free Wifi
1,OYO Flagship Hotel Lavish Stay,New Santoshnagar,['Hyderabad'],['4.3'],['23'],₹582,Free Wifi Geyser Power backup
2,OYO Flagship Hotel Shazeb International,Telangana,['Hyderabad'],['3.7'],['17'],₹699,Elevator Free Wifi Geyser
3,Collection O Hotel Rbs Kothapet-nagole Road,NaN,['Hyderabad'],['5.0'],['7'],₹699,Elevator Free Wifi Geyser
4,OYO Flagship 80983G RBS Square Langer Houz,Hyderabad,"['Hyderabad', 'Hyderabad']",['3.9'],['98'],₹699,Free Wifi Geyser Power backup
...,...,...,...,...,...,...,...
357,Collection O 815331 Hotel Galaxy Shelter,Prabhadevi. Appasaheb Marathe Marg,['Mumbai'],['3.6'],['10'],₹3902,Elevator Free Wifi Geyser
358,Capital O Hotel Pearl Near US Embassy,"Near Wajan Kata Bus Stop, Indira Nagar",['Mumbai'],['3.3'],['160'],₹2896,Free Wifi CCTV cameras Card payment
359,OYO Townhouse 810 Royal Palms Hotel - Daisy Co...,Goregaon,['Mumbai'],['3.6'],['494'],₹3773,Parking facility Free Wifi Power backup
360,OYO Hotel Ak Palace Near Chhatrapati Shivaji I...,"On main street, Near Asalpha Metro Station, Sa...",['Mumbai'],['3.1'],['254'],NaN,Free Wifi
361,OYO Flagship Raj Hotel Near Juhu Beach,Santacruz,['Mumbai'],['3.1'],['191'],NaN,Free Wifi Geyser Power backup